[2025-03-20T13:38:52.758+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T13:38:52.787+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: store_json_to_postgres.insert_json_to_db manual__2025-03-20T13:23:46.959243+00:00 [queued]>
[2025-03-20T13:38:52.800+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: store_json_to_postgres.insert_json_to_db manual__2025-03-20T13:23:46.959243+00:00 [queued]>
[2025-03-20T13:38:52.801+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 4
[2025-03-20T13:38:52.822+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): insert_json_to_db> on 2025-03-20 13:23:46.959243+00:00
[2025-03-20T13:38:52.834+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1864) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-20T13:38:52.836+0000] {standard_task_runner.py:72} INFO - Started process 1865 to run task
[2025-03-20T13:38:52.838+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'store_json_to_postgres', 'insert_json_to_db', 'manual__2025-03-20T13:23:46.959243+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/store_json_to_postgres.py', '--cfg-path', '/tmp/tmpfi4zioa0']
[2025-03-20T13:38:52.844+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask insert_json_to_db
[2025-03-20T13:38:52.861+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-20T13:38:52.915+0000] {task_command.py:467} INFO - Running <TaskInstance: store_json_to_postgres.insert_json_to_db manual__2025-03-20T13:23:46.959243+00:00 [running]> on host 6adff4754eb0
[2025-03-20T13:38:53.047+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='store_json_to_postgres' AIRFLOW_CTX_TASK_ID='insert_json_to_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T13:23:46.959243+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T13:23:46.959243+00:00'
[2025-03-20T13:38:53.049+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T13:38:53.073+0000] {store_json_to_postgres.py:22} INFO - Checking file: /opt/***/Output/Nepal_Profile.json
[2025-03-20T13:38:53.074+0000] {store_json_to_postgres.py:45} ERROR - Failed: File not found: /opt/***/Output/Nepal_Profile.json
[2025-03-20T13:38:53.075+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_json_to_postgres.py", line 24, in insert_json_to_postgres
    raise FileNotFoundError(f"File not found: {SOURCE_JSON_PATH}")
FileNotFoundError: File not found: /opt/***/Output/Nepal_Profile.json
[2025-03-20T13:38:53.093+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=store_json_to_postgres, task_id=insert_json_to_db, run_id=manual__2025-03-20T13:23:46.959243+00:00, execution_date=20250320T132346, start_date=20250320T133852, end_date=20250320T133853
[2025-03-20T13:38:53.133+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T13:38:53.135+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 28 for task insert_json_to_db (File not found: /opt/***/Output/Nepal_Profile.json; 1865)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_json_to_postgres.py", line 24, in insert_json_to_postgres
    raise FileNotFoundError(f"File not found: {SOURCE_JSON_PATH}")
FileNotFoundError: File not found: /opt/***/Output/Nepal_Profile.json
[2025-03-20T13:38:53.187+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-20T13:38:53.231+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-20T13:38:53.235+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
